#!/usr/bin/env bash
#  10-fizzbuzz: Thos script prints out 1 to 100,7 with
#+ special requirements

for i in {1..100..1}
do
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
    then
	echo FizzBuzz
    elif [ $((i % 3)) -eq 0 ]
    then
	echo Fizz
    elif [ $((i % 5)) -eq 0 ]
    then
	echo Buzz
    else
	echo $i
    fi
done


