#!/usr/bin/env bash
#  This script displays 'bad luck' for the 4th loop iteration
#+ 	       displays 'good luck' for the 8th loop iteration
#+             displays 'Best School' for the other iterations

i="0"

while [ $i -lt 20 ]
do
    echo $((i+1))
    case $i in
       3) echo "bad luck from China";;
       
       8) echo "bad luck from Japan";;
       
       16) echo "bad luck from Italy";;
       
       *) :;;
       
     esac
      i=$((i+1))
done
