#!/usr/bin/env bash
#  This script displays 'bad luck' for the 4th loop iteration
#+ 	       displays 'good luck' for the 8th loop iteration
#+             displays 'Best School' for the other iterations

i="0"

while [ $i -lt 20 ]
do
    echo $((i+1))
      if [ $i -eq 3 ]
      then
	echo "bad luck from China"
      elif [ $i -eq 8 ]
      then
	  echo "bad luck from Japan"
      elif [ $i -eq 16 ]
      then
	  echo "bad luck from Italy"
      else
	:
      fi
      i=$((i+1))
done
