#!/usr/bin/env bash
#  7-clock: This script displays the time for 12 hours and 59 minutes

hour=0
minute=0

while [ $hour -le 13 ]
do
	if [ $((minute % 60)) -eq 0 ]
	then
	    minute=1
	    if [ $hour -le 12 ]
	    then
		echo "Hour: $hour"
	    else
		exit 0
	    fi
	   hour=$((hour+1))
	fi

	echo $minute
	minute=$((minute+1))
done



