#!/usr/bin/env bash
#  8-for_ls: This script displays the content s of the
#+ current directory in lost format after formatting
#+ every item by removing every character before and
#+ including the dash

dirlist=($(ls *))

for i in "${dirlist[@]}"
do
    echo "$(echo "$i" | sed -r 's/.-//')"
done

